contact_links:
  - name: 💡 Feature Request
    url: https://github.com/ptarmiganlabs/qs-util/discussions/new
    about: Share ideas for new features
  - name: ❓ Question
    url: https://github.com/ptarmiganlabs/qs-util/discussions/new
    about: General questions
  - name: 🪲 Bug report
    url: https://github.com/ptarmiganlabs/qs-util/issues/new
    about: Something isn't working?
